cut_body_after = "" # don't include text from the PR body in the merge commit message
status = [
  "Evaluate flake.nix",
  "build",
  "check generated-flake-is-same [x86_64-linux]",
  "check install-nixos [x86_64-linux]",
  "check kuutamod [x86_64-linux]",
  "check kuutamod-lint [x86_64-linux]",
  "check kuutamod-unit-tests [x86_64-linux]",
  "check kuutamod-unit-tests-unstable [x86_64-linux]",
  "check neard [x86_64-linux]",
  "check treefmt [x86_64-linux]",
  "devShell default [x86_64-linux]",
  "nixosConfig single-node-validator-mainnet",
  "nixosConfig single-node-validator-testnet",
  "nixosConfig validator-00",
  "package default [x86_64-linux]",
  "package kuutamo [x86_64-linux]",
  "package kuutamod [x86_64-linux]",
  "package near-bin [x86_64-linux]",
  "package near-cli [x86_64-linux]",
  "package neard [x86_64-linux]",
  "package neard-unstable [x86_64-linux]",
  "package nix-update [x86_64-linux]",
  "package treefmt [x86_64-linux]"
]
