[package]
name = "kuutamod"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reqwest = { version = "0.11.12", features = ["json"], default-features = false }
anyhow = "1.0.65"
tokio = { version = "1.21.2", features = ["full"] }
futures-util = "0.3.24"
hyper = { version = "0.14.20", features = [ "server" ] }
prometheus = "0.13.2"
lazy_static = "1.4.0"
nix = "0.25.0"
serde = { version = "1.0.145", features = ["derive"] }
serde_json = "1.0.85"
near-primitives = "0.14.0"
log = { version = "0.4.17", features = ["std"] }
clap = { version = "4.0.11", features = ["derive", "env"] }

[[bin]]
name = "kuutamod"
path = "src/bin/kuutamod.rs"

[[bin]]
name = "kuutamoctl"
path = "src/bin/kuutamoctl.rs"
