[package]
name = "kuutamod"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reqwest = { version = "0.11.11", features = ["json"], default-features = false }
anyhow = "1.0.59"
tokio = { version = "1.21.2", features = ["full"] }
futures-util = "0.3.21"
hyper = { version = "0.14.20", features = [ "server" ] }
prometheus = "0.13.1"
lazy_static = "1.4.0"
nix = "0.24.2"
serde = { version = "1.0.142", features = ["derive"] }
serde_json = "1.0.83"
near-primitives = "0.14.0"
log = { version = "0.4.17", features = ["std"] }
clap = { version = "3.2.16", features = ["derive", "env"] }

[[bin]]
name = "kuutamod"
path = "src/bin/kuutamod.rs"

[[bin]]
name = "kuutamoctl"
path = "src/bin/kuutamoctl.rs"
