[package]
name = "kuutamod"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reqwest = { version = "0.11.13", features = ["json"], default-features = false }
anyhow = "1.0.66"
tokio = { version = "1.22.0", features = ["full"] }
hyperlocal = "0.8"
futures-util = "0.3.25"
hyper = { version = "0.14.23", features = [ "server" ] }
prometheus = "0.13.3"
lazy_static = "1.4.0"
nix = "0.26.1"
serde = { version = "1.0.148", features = ["derive"] }
serde_json = "1.0.89"
near-primitives = "0.15.0"
log = { version = "0.4.17", features = ["std"] }
clap = { version = "4.0.29", features = ["derive", "env"] }

[[bin]]
name = "kuutamod"
path = "src/bin/kuutamod.rs"

[[bin]]
name = "kuutamoctl"
path = "src/bin/kuutamoctl.rs"
